# Generated by Django 6.0 on 2026-05-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitycourse',
            old_name='course_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='universitycourse',
            name='intake',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
