# Generated by Django 6.0 on 2026-05-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_course_name_universitycourse_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('average_fee', models.CharField(max_length=100)),
                ('career_opportunities', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('universities', models.JSONField(default=list)),
            ],
        ),
    ]
